/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.airline_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author iamsa
 */
public class AddFlight extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddCustomer
     */
    public AddFlight() {
        initComponents();
        AutoID();
    }
    
     public void AutoID(){
        
        try {
            Connection con;
            PreparedStatement pre;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/Airline_Reservation","root","1436");
            
            pre = con.prepareStatement("Select Max(FlightID) from Flight");
            
            ResultSet rs = pre.executeQuery();
            rs.next();
            
            if(rs.getString("MAX(FlightID)") == null){
                flightid.setText("FL001");
            }else{
                long id = Long.parseLong(rs.getString("MAX(FlightID)").substring(2));
                id++;
                flightid.setText("FL"+String.format("%03d", id));
               
            }
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        flightid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        seats = new javax.swing.JTextField();
        fare = new javax.swing.JTextField();
        duration = new javax.swing.JTextField();
        flightname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        arrival = new javax.swing.JTextField();
        departure = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dof = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setClosable(true);
        setForeground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Patrick Hand SC", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Date Of Flight :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 230, 160, 20);

        flightid.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        flightid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightidActionPerformed(evt);
            }
        });
        jPanel1.add(flightid);
        flightid.setBounds(110, 20, 100, 23);

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Patrick Hand SC", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Flight ID :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 20, 120, 20);

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Patrick Hand SC", 3, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Flight Name :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 70, 140, 22);

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("Patrick Hand SC", 3, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Duration :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 310, 120, 20);

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setFont(new java.awt.Font("Patrick Hand SC", 3, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Seats :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(360, 10, 90, 20);

        seats.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel1.add(seats);
        seats.setBounds(420, 10, 130, 23);

        fare.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel1.add(fare);
        fare.setBounds(70, 140, 130, 23);

        duration.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationActionPerformed(evt);
            }
        });
        jPanel1.add(duration);
        duration.setBounds(110, 310, 120, 23);

        flightname.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        flightname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightnameActionPerformed(evt);
            }
        });
        jPanel1.add(flightname);
        flightname.setBounds(120, 70, 140, 23);

        jLabel11.setBackground(new java.awt.Color(204, 204, 255));
        jLabel11.setFont(new java.awt.Font("Patrick Hand SC", 3, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Arrival :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(360, 60, 90, 20);

        jLabel12.setBackground(new java.awt.Color(204, 204, 255));
        jLabel12.setFont(new java.awt.Font("Patrick Hand SC", 3, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Departure :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(360, 120, 120, 20);

        jButton1.setFont(new java.awt.Font("SimSun", 1, 10)); // NOI18N
        jButton1.setText("Add Flight");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 350, 110, 23);

        jButton2.setFont(new java.awt.Font("SimSun", 1, 10)); // NOI18N
        jButton2.setText("Delete Flight");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(470, 350, 110, 23);

        arrival.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        arrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalActionPerformed(evt);
            }
        });
        jPanel1.add(arrival);
        arrival.setBounds(430, 60, 130, 23);

        departure.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        departure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureActionPerformed(evt);
            }
        });
        jPanel1.add(departure);
        departure.setBounds(450, 120, 120, 23);

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("Patrick Hand SC", 3, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Fare :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 140, 140, 20);
        jPanel1.add(dof);
        dof.setBounds(150, 230, 120, 22);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Patrick Hand SC", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Airline Reservation System\\Airline_Management_System\\src\\main\\resources\\flightbook_internal_2.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 600, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 50, 600, 400);

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel2.setText("Welcome to Flight Pannel");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 10, 250, 30);

        jLabel1.setForeground(java.awt.SystemColor.activeCaption);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Airline Reservation System\\Airline_Management_System\\src\\main\\resources\\flightbook_2.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flightidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightidActionPerformed

    private void flightnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightnameActionPerformed

    private void durationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
            // TODO add your handling code here:
  try {
            
//        Extracting Values From Add Flight Form.


        String FlightID = flightid.getText();
        String FlightName = flightname.getText();
        String Arrival =  arrival.getText();
        String Departure = departure.getText();
        String Duration = duration.getText();
        String Seats = seats.getText();
        String Fare = fare.getText();
        DateFormat da = new SimpleDateFormat("yyyy-MM-dd");
        String Date = da.format(dof.getDate());
        
        




//      Datat Base Connection


        Connection con;
        PreparedStatement pre;
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/Airline_Reservation","root","1436");
        
        
//    Adding Values to Database.


        pre = con.prepareStatement("Insert into Flight(FlightID,FlightName,Arrival,Departure,Duration,Seats,Fare,Date) values(?,?,?,?,?,?,?,?)");
        
        pre.setString(1,FlightID );
        pre.setString(2,FlightName );
        pre.setString(3,Arrival );
        pre.setString(4,Departure );
        pre.setString(5,Duration );
        pre.setString(6,Seats );
        pre.setString(7,Fare );
        pre.setString(8,Date );
        
        
        pre.executeUpdate();
        
        
        JOptionPane.showMessageDialog(null, "Added Flight SucessFully");
        
        
        








//          Catch Clause

 
 }      catch (ClassNotFoundException ex) {
            Logger.getLogger(AddFlight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
  
  
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void arrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivalActionPerformed

    private void departureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrival;
    private javax.swing.JTextField departure;
    private com.toedter.calendar.JDateChooser dof;
    private javax.swing.JTextField duration;
    private javax.swing.JTextField fare;
    private javax.swing.JTextField flightid;
    private javax.swing.JTextField flightname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField seats;
    // End of variables declaration//GEN-END:variables
}
