/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.airline_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iamsa
 */
public class BookFlight extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddCustomer
     */
    public BookFlight() {
        initComponents();
        AutoID();
    }
    
    String flightid;
    
    
     public void AutoID(){
        
        try {
            Connection con;
            PreparedStatement pre;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/Airline_Reservation","root","1436");
            
            pre = con.prepareStatement("Select Max(TicketID) from Ticket");
            
            ResultSet rs = pre.executeQuery();
            rs.next();
            
            if(rs.getString("MAX(TicketID)") == null){
                ticketid.setText("TK001");
            }else{
                long id = Long.parseLong(rs.getString("MAX(TicketID)").substring(2));
                id++;
                ticketid.setText("TK"+String.format("%03d", id));
               
            }
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        departure = new javax.swing.JComboBox<>();
        arrival = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        not = new javax.swing.JTextField();
        totalfare = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        customerid = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        fare = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ticketid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setForeground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(790, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("Departure");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 50, 90, 20);

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("Arrival");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 50, 80, 20);

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setText("Search Flight");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 10, 120, 20);

        departure.setFont(new java.awt.Font("SimSun", 1, 10)); // NOI18N
        departure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mumbai", "Pune", "Delhi", "Hyderabad", "Goa", "Banglore" }));
        jPanel1.add(departure);
        departure.setBounds(210, 80, 72, 18);

        arrival.setFont(new java.awt.Font("SimSun", 1, 10)); // NOI18N
        arrival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mumbai", "Pune", "Delhi", "Hyderabad", "Goa", "Banglore" }));
        jPanel1.add(arrival);
        arrival.setBounds(20, 80, 72, 18);

        jButton1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 127, 80, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Airline Reservation System\\Airline_Management_System\\src\\main\\resources\\bookFlight_Search_3.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 330, 160);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 330, 160);

        table.setFont(new java.awt.Font("SimSun", 0, 10)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Flight Name", "Arrival", "Departure", "Duration", "Date"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 280, 470, 150);

        jLabel2.setFont(new java.awt.Font("Patrick Hand SC", 2, 22)); // NOI18N
        jLabel2.setText("Book Your's  Dream Flight noww ...");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 0, 280, 30);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel8.setText("Discount :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 330, 70, 15);

        jLabel9.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel9.setText("Contact :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 170, 70, 15);

        jLabel10.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel10.setText("Gender :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 130, 70, 15);

        jLabel11.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel11.setText("Fare :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 210, 70, 15);

        jLabel12.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel12.setText("Total-Tickets :");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 250, 100, 15);

        jLabel13.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel13.setText("Total Fare :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 290, 100, 20);

        jLabel14.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel14.setText("Customer Id :");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 10, 90, 15);

        jLabel15.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel15.setText("First Name :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 50, 80, 15);

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel2.add(firstname);
        firstname.setBounds(100, 50, 90, 30);

        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel2.add(lastname);
        lastname.setBounds(100, 90, 90, 30);

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel2.add(contact);
        contact.setBounds(70, 170, 100, 30);

        not.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notActionPerformed(evt);
            }
        });
        jPanel2.add(not);
        not.setBounds(100, 250, 50, 22);

        totalfare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalfareActionPerformed(evt);
            }
        });
        jPanel2.add(totalfare);
        totalfare.setBounds(90, 290, 90, 22);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6);
        jTextField6.setBounds(90, 330, 90, 22);

        customerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeridActionPerformed(evt);
            }
        });
        jPanel2.add(customerid);
        customerid.setBounds(100, 10, 90, 30);

        male.setFont(new java.awt.Font("SimSun", 1, 10)); // NOI18N
        male.setText("Male");
        jPanel2.add(male);
        male.setBounds(70, 130, 70, 20);

        female.setFont(new java.awt.Font("SimSun", 1, 10)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel2.add(female);
        female.setBounds(130, 130, 98, 20);

        jLabel16.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel16.setText("Last Name :");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 90, 70, 15);

        fare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fareActionPerformed(evt);
            }
        });
        jPanel2.add(fare);
        fare.setBounds(60, 210, 110, 22);

        jButton2.setFont(new java.awt.Font("SimSun", 1, 10)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(200, 10, 70, 20);

        jButton4.setFont(new java.awt.Font("SimSun", 1, 10)); // NOI18N
        jButton4.setText("Book");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(10, 360, 90, 20);

        jButton5.setFont(new java.awt.Font("SimSun", 1, 10)); // NOI18N
        jButton5.setText("Cancel");
        jPanel2.add(jButton5);
        jButton5.setBounds(170, 360, 90, 20);

        jButton6.setFont(new java.awt.Font("SimSun", 1, 10)); // NOI18N
        jButton6.setText("Calculate Fare");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(160, 250, 110, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Airline Reservation System\\Airline_Management_System\\src\\main\\resources\\bookFlight_Search_4 (1).jpg")); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 280, 390);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(490, 50, 280, 390);

        jLabel18.setFont(new java.awt.Font("Source Code Pro Light", 0, 12)); // NOI18N
        jLabel18.setText("Ticket ID : ");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(550, 10, 90, 20);

        ticketid.setFont(new java.awt.Font("SimSun", 0, 10)); // NOI18N
        ticketid.setText("ticket Id");
        getContentPane().add(ticketid);
        ticketid.setBounds(640, 10, 90, 20);

        jLabel1.setForeground(java.awt.SystemColor.activeCaption);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Airline Reservation System\\Airline_Management_System\\src\\main\\resources\\pascal-meier-UYiesSO4FiM-unsplash (1).jpg")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1080, 764));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void notActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notActionPerformed

    private void totalfareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalfareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalfareActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void customeridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customeridActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void fareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fareActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        try {
            // TODO add your handling code here:
//            Extraction of variables
                
            String CustomerID = customerid.getText();
            
            
            
//            Connection 
            Connection con;
            PreparedStatement pre;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/Airline_Reservation","root","1436");
            
//         Searching logic

            pre = con.prepareStatement("Select * from Customer where CustomerID=?");
            
            pre.setString(1, CustomerID);
            
            ResultSet rs = pre.executeQuery();
            
            if(rs.next() != false){
                
                firstname.setText(rs.getString("FirstName"));
                lastname.setText(rs.getString("LastName"));
                contact.setText(rs.getString("Contact"));
                
                if(rs.getString("Gender").equals("Male")){
                    male.setSelected(true);
                }else if (rs.getString("Gender").equals("Female")){
                    female.setSelected(true);
                }
                
                
            }else{
                JOptionPane.showMessageDialog(null, "Customer Doesnot Exists :(  ");
            }
            
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SearchCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SearchCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
  
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            
            
//            Extraction of values from form.
        




            




        


            String TicketID = ticketid.getText();
            String FlightID = flightid;
            String CustomerID = customerid.getText();
            String Arrival = arrival.getSelectedItem().toString();
            String Departure = departure.getSelectedItem().toString();
            String FirstName = firstname.getText();
            String LastName = lastname.getText();
            String Gender;
            if(male.isSelected()){
                Gender = "Male";
            }else{
                Gender = "Female";
            }
            String Contact = contact.getText();
            
            
            






            
//            Connecting Database.
            Connection con;
            PreparedStatement pre;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/Airline_Reservation","root","1436");
            
            
            pre = con.prepareStatement("Insert into Ticket(TicketID,FlightID,CustomerID,Arrival,Departure,FirstName,LastName,Gender,Contact)values(?,?,?,?,?,?,?,?,?)");
            
            pre.setString(1, TicketID);
            pre.setString(2,FlightID);
            pre.setString(3,CustomerID);
            pre.setString(4,Arrival);
            pre.setString(5,Departure);
            pre.setString(6,FirstName);
            pre.setString(7,LastName);
            pre.setString(8,Gender);
            pre.setString(9,Contact);
            
            pre.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Hooraay ! Booked Flight Sucessfully");
                 
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
        
 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
             /*    Extraction of Data       */
            String Arrival = arrival.getSelectedItem().toString();
            String Departure = departure.getSelectedItem().toString();
            
            
            /*     Dtata Base Cconnection        */
            Connection con;
            PreparedStatement pre;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/Airline_Reservation","root","1436");
            
             /*     Dtata Base Manipulation   */
             
             pre = con.prepareStatement("Select * from flight where arrival=? and departure=?");
             
             pre.setString(1,Arrival);
             pre.setString(2,Departure);
             
             ResultSet rs = pre.executeQuery();
             
             ResultSetMetaData rsmd = rs.getMetaData();
             
             int col = rsmd.getColumnCount();
             
             DefaultTableModel DFT = (DefaultTableModel) table.getModel();
             
             while(rs.next()){
                 Vector v = new Vector();
                 
                 for(int i = 1 ; i < col ; i++){
                     v.add(rs.getString("FlightID"));
                     v.add(rs.getString("FlightName"));
                     v.add(rs.getString("Arrival"));
                     v.add(rs.getString("Departure"));
                     v.add(rs.getString("Duration"));
                     v.add(rs.getString("Date"));
                 }
                 DFT.addRow(v);
             }
        
        } 
        
         /*     Cath Clause        */
        
        catch (ClassNotFoundException ex) {
            Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        int cost = Integer.parseInt(fare.getText());
        
        int tickets = Integer.parseInt(not.getText());
        
        totalfare.setText(cost*tickets+"");
        
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try {
            // TODO add your handling code here:
            
            
//            Extraction of flight id
            
            int col = 0;
            int row = table.getSelectedRow();
            
            flightid = table.getModel().getValueAt(row, col).toString();
            
            
            
//            Connencting to database
            Connection con;
            PreparedStatement pre;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/Airline_Reservation","root","1436");
            
//            Manipulation database.

              pre = con.prepareStatement("Select Fare from flight where FlightID=?");
              
              pre.setString(1, flightid);
              
              ResultSet rs = pre.executeQuery();
              
              rs.next();
              
              fare.setText(rs.getString("Fare"));
            
            
            
    
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> arrival;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField customerid;
    private javax.swing.JComboBox<String> departure;
    private javax.swing.JTextField fare;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField lastname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField not;
    private javax.swing.JTable table;
    private javax.swing.JLabel ticketid;
    private javax.swing.JTextField totalfare;
    // End of variables declaration//GEN-END:variables
}
